#! /usr/bin/env ruby

require './operation'
require './check_input'

class Main
  include CheckInput
  
  def initialize
    @operation = Operation.new
    @option = ''
  end

  def menu_content
    puts "\nPlease choose an option by entering a number:"
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for a given person id'
    puts '7 - Exit'
  end

  def menu
    menu_content
    @option = check_input('') { %w[1 2 3 4 5 6 7].include?(@option) }
  end

  def main
    loop do
      case @option = menu
      when '1'
        @operation.list_all_books
      when '2'
        @operation.list_all_people
      when '3'
        @operation.create_a_person
      when '4'
        @operation.create_a_book
      when '5'
        @operation.create_a_rental
      when '6'
        @operation.list_all_rentals
      else
        puts "Thank you for using this app!\n"
        break
      end
    end
  end
end

puts 'Welcome to School Library App!'
school_library = Main.new
school_library.main
