#! /usr/bin/env ruby

require './all_rentals'
require './check_input'
require './app'
require './all_books'
require './all_peoples'
require './json'

class Main
  include CheckInput
  include Json_IO

  def initialize
    @app = App.new
    @allrentals = AllRentals.new(@app)
    @allbooks = AllBooks.new(@app)
    @allpeople = AllPeoples.new(@app)
    @option = ''
  end

  def menu_content
    puts "\nPlease choose an option by entering a number:"
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for a given person id'
    puts '7 - Exit'
  end

  def menu
    menu_content
    @option = check_input('') { %w[1 2 3 4 5 6 7].include?(@option) }
  end

  def main
    loop do
      case @option = menu
      when '1'
        @allbooks.list_all_books
      when '2'
        @allpeople.list_all_people
      when '3'
        @allpeople.create_a_person
      when '4'
        @allbooks.create_a_book
      when '5'
        @allrentals.create_a_rental
      when '6'
        @allrentals.list_all_rentals
      else
        writer
        puts "Thank you for using this app!\n"
        break
      end
    end
  end
end

puts 'Welcome to School Library App!'
school_library = Main.new
school_library.main
